---
- name: open apiserver port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "6443"
    jump: ACCEPT

- name: open kubelet metrics port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "10250"
    jump: ACCEPT

- name: open HA support ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "2379:2380"
    jump: ACCEPT

- name: install k3s and start HA cluster
  shell: curl -sfL https://get.k3s.io | sh -s server --cluster-init

- name: get cluster node token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: save secret into dummy host
  add_host:
    name: "k3_init_dummy"
    k3s_token: "{{ node_token.stdout }}"

- name: make sure k3s is started and enabled
  service:
    name: k3s
    state: started
    enabled: yes

- name: get kube config for local cluster access
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/home/ken/.kube/config
    remote_src: yes
    owner: "ken"
    mode: "600"
