- name: open k3s apiserver port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "6443"
    jump: ACCEPT

- name: open kubelet metrics port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "10250"
    jump: ACCEPT

- name: open k3s HA for embedded etc ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "2379:2380"
    jump: ACCEPT

- name: open k3s HA for embedded etcd ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "2379:2380"
    jump: ACCEPT

- name: download k3s binary
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/v1.23.5+k3s1/k3s-arm64
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
