- name: install keepalived
  apt:
    name:
    - keepalived
    state: latest

- name: upload keepalived backup configs
  template:
    src: templates/keepalived.conf
    dest: /etc/keepalived/keepalived.conf
    backup: yes

- name: restart and enable keepalived service
  service:
    name: keepalived
    state: restarted
    enabled: yes
