
- name: k3s base installation
  hosts: magi
  remote_user: root
  roles:
    - ../roles/k3sup

- name: k3s cluster initialization
  hosts: magi[0]
  remote_user: root
  roles:
    - ../roles/k3sup-init

- name: k3s cluster join
  hosts: magi[1:2]
  remote_user: root
  roles:
    - ../roles/k3sup-join
